# Generated by Django 3.2.16 on 2022-11-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
