# Generated by Django 3.2.16 on 2022-11-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMP', '0003_addall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addall',
            name='DOB',
        ),
    ]
